### ISSUE TITLE
Requires trusted certificate.  How to bypass and use self-signed cert?

### ISSUE THREAD

**Issue by megamegamega** [AxisCommunications/goalie-url-shortener#8]
nginx_1    | 2019/01/24 16:49:34 [emerg] 1#1: PEM_read_bio_X509_AUX("/run/secrets/go_https_crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)

**Comment by AntonFriberg** [comment]
Thanks for the issue!

I will start working on making the initial setup easier. Will get back to you after the weekend!

**Comment by AntonFriberg** [comment]
Hi!

@megamegamega I have removed the ssl encryption for the initial setup and added setup documentation to the README.md . Note that you currently need LDAP connection to login to the frontend. I am working on allowing other forms of authentication.

**Comment by megamegamega** [comment]
Hi Anton!

Thanks for being awesome.  I'm able to access the tool via port 80 now.  

Regards,
MegaMegaMega
